# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 996d8f2ff7a0749cabcc72537615161d481f7272c41c55af1920f38196a802892ece755c80fcf19d68dd6a190b9525e24ae4c7b09f81dce092a5ebb314affab5

test:
  secret_key_base: 3143d1066f74a7875d2bedfbd09081182fe940bc6ac15693500f8322a7b5b15641d31f9577a92036c2d4925f430f0fe52300890b9ed0a7e24dea5f8164b3e75a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
